name: Coke_test
description: Saved on 2025-10-30 13:57
created_at: '2025-10-30T13:57:13.800871'
filters:
  use_lower: true
  lower_value: 1
  use_acv: true
  acv_value: 10
  use_cot: true
  cot_value: Food
  use_promo: true
  promo_value: 0
  exclude_zeros: true
regression:
  dependent_var: Auto_Base_Units
  continuous_vars:
  - ACV_Weighted_Distribution
  categorical_vars:
  - Account
  - Price_Bucket_Quarter
kfold:
  n_splits: 8
  group_column: 13_Week_Periods
  account_column: Account
  weight_column: Auto_Base_Units
outlier:
  contamination: 0.06
  eps_percentile: 90
  dbscan_min_samples: 5
  hdbscan_min_cluster_size: 5
  use_dbcv: true
